### ISSUE TITLE
MS SQL Service Broker - will it work ?

### ISSUE THREAD

**Issue by thewayibyte** [osjoberg/LinqCache#2]
Hi,

Currently I'm working with EF and I'm trying to use the MS SQL Service Broker for notofications from DB. 
For the Code-First approach it works perfectly fine. But now I want to get this with EDMX model generated based on existing database. 

Would you mind helping me with this ?
As far as I'm concerned I think that the Cashing thingy should be used in EDMX..

**Comment by osjoberg** [comment]
Hello,

First of all, thank you for reporting this issue! Although Entity Framework Database First was an untested scenario, your query made me try it out, and I got it working. I will add unit-tests for this in the next release. However there might be something specific in your scenario that does not work and I am interested in making it work for you, so can you help me with more information. What is not working, do you get any exception? Thanks in advance.

**Comment by thewayibyte** [comment]
Generally the question is how to "join" the EDMX model with the SqlDependency. 
If I'm using the EDMX and I change something in the database nothing is coming to my application. If I use the standard Code-First approach (without the EDMX model) then it works perfectly fine.

**Comment by osjoberg** [comment]
Debugging this can be hard sometimes. What version of SQL-Server are you using? Are you testing both database first and code first with the same database and connection string?

**Comment by thewayibyte** [comment]
1. And I have 2 different connectionStrings, one for Code-first and second for EDMX

**Comment by thewayibyte** [comment]
I can send you the code if you want to take a look at that :)

**Comment by osjoberg** [comment]
Sure, send me the code and I can have a look at it!

**Comment by thewayibyte** [comment]
Okay, Hi.
so I have my code in files attached.
The table model:
 public partial class IS_Pages_Visits
    {
        public int Id { get; set; }
        public string Where { get; set; }
        public string Project { get; set; }
        public string What { get; set; }
        public string Who { get; set; }
        public Nullable<System.DateTime> When { get; set; }
        public string How { get; set; }
    }

Then I have repository class (attached(). Then i have the global class
(attached, this is the config file)
will that be enough?

2014-12-19 16:55 GMT+01:00 osjoberg notifications@github.com:

> Sure, send me the code and I can have a look at it!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/osjoberg/LinqCache/issues/2#issuecomment-67655865.
> 
> ﻿using System;
> using System.Collections.Generic;
> using System.Configuration;
> using System.Data;
> using System.Data.SqlClient;
> using System.IO;
> using System.Linq;
> using Analytics.Repository.Entities;
> using Analytics.Repository.Extensions;
> using Analytics.Repository.Hubs;
> using Microsoft.AspNet.SignalR;

namespace Analytics.Repository.Repositories
{
    public class AnalyticsRepository : Hub
    {
        //private readonly string _connString = ConfigurationManager.ConnectionStrings["Intranet_ISAnalyticsEntities1"].ConnectionString;

```
    public IList<AnalyticsRow> GetAllVisits(string query, Enums.Enums.TABLES table, string _connString)
    {
        return MakeACall(query, table, _connString);
    }

    public IList<AnalyticsRow> GetAllKPIs(string query, Enums.Enums.TABLES table, string _connString)
    {
        return MakeACall(query, table, _connString);
    }

    private IList<AnalyticsRow> MakeACall(string query, Enums.Enums.TABLES table, string _connString)
    {
        var rows = new List<AnalyticsRow>();
        using (var connection = new SqlConnection(_connString))
        {
            connection.Open();
            using (var command = new SqlCommand(query, connection))
            {
                command.Notification = null;

                var dependency = new SqlDependency(command);
                switch (table)
                {
                    case Enums.Enums.TABLES.IS_KPI_Submitted:
                        dependency.OnChange += new OnChangeEventHandler(IS_KPI_Submitted_OnChange);
                        break;
                    case Enums.Enums.TABLES.IS_Pages_Visits:
                        dependency.OnChange += new OnChangeEventHandler(IS_Pages_Visits_OnChange);
                        break;
                    case Enums.Enums.TABLES.IS_RTH_Updates:
                        break;
                    default:
                        throw new ArgumentOutOfRangeException("table");
                }


                if (connection.State == ConnectionState.Closed)
                    connection.Open();

                var reader = command.ExecuteReader();

                while (reader.Read())
                {
                    var row = new AnalyticsRow();
                    if (reader.HasColumn("Id")) row.Id = (int)reader["Id"];
                    if (reader.HasColumn("What")) row.What = (string)reader["What"];
                    if (reader.HasColumn("Project")) row.Project = (string)reader["Project"];
                    rows.Add(row);
                }
            }
        }
        return rows;
    }

    private void IS_KPI_Submitted_OnChange(object sender, SqlNotificationEventArgs e)
    {
        if (e.Type == SqlNotificationType.Change)
        {
            AnalyticsHub.GetKPIs();
        }
    }

    private void IS_Pages_Visits_OnChange(object sender, SqlNotificationEventArgs e)
    {
        if (e.Type == SqlNotificationType.Change)
        {
            AnalyticsHub.GetVisits();
        }
    }
}
```

}
﻿  string connString = ConfigurationManager.ConnectionStrings["Intranet_ISAnalyticsEntities1"].ConnectionString;

```
    private static Intranet_ISAnalyticsEntities1 context = new Intranet_ISAnalyticsEntities1();

    protected void Application_Start()
    {
        AreaRegistration.RegisterAllAreas();

        WebApiConfig.Register(GlobalConfiguration.Configuration);
        FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
        RouteConfig.RegisterRoutes(RouteTable.Routes);
        BundleConfig.RegisterBundles(BundleTable.Bundles);
        AuthConfig.RegisterAuth();

        //Start SqlDependency with application initialization
        SqlDependency.Start(context.Database.Connection.ConnectionString);
    }


    protected void Application_End()
    {
        //Stop SQL dependency
        SqlDependency.Stop(connString);
    }
```

**Comment by osjoberg** [comment]
Hello! Your code does not seem complete so I am unable to test it completely. One non-obvious thing that I can see is that you need to do is to register the SqlDependency with Entity Framework. You do this by calling:

CallContext.SetData("MS.SqlDependencyCookie", dependency.Id);

You will want to do this after you created your dependency but before you run the query you wish to monitor.

Also you will want to unregister the dependency from Entity Framework when you do not need it anymore.

CallContext.FreeNamedDataSlot("MS.SqlDependencyCookie");

Just because I am curious, why did you not settle to use the LinqCache library to solve this?
